name: ci

on:
  push:
    branches:
      - "1.0.1"

jobs:
  build:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Publish to Docker Hub
        uses: docker/build-push-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/warehouse:latest
